"""Refusal / redirect node.

Reached when the input guard returns a hard block. The message was written by
the guard that fired, so this node delivers it verbatim: a student in distress
should not receive a paraphrase generated by the same model that was just
stopped from answering.
"""

from __future__ import annotations

import logging
from typing import Any, Optional

from langchain_core.runnables import RunnableConfig

from app.agents.state import AgentDeps, AgentState, get_deps

logger = logging.getLogger(__name__)

_DEFAULT_REFUSAL = (
    "That's not something I can help with. I'm here for schoolwork though -- "
    "pick any subject and I'll get started."
)


async def refuse_node(
    state: AgentState, config: RunnableConfig
) -> dict[str, Any]:
    """Emit the guard's message as the answer for this turn.

    Args:
        state: Current agent state; ``draft`` holds the guard's message.
        config: LangGraph config carrying :class:`AgentDeps`.

    Returns:
        A partial state update with ``final_answer``.
    """
    deps: AgentDeps = get_deps(config)
    message = (state.get("draft") or "").strip() or _DEFAULT_REFUSAL
    logger.info("Refusal node delivering guard message for session %s.", state.get("session_id"))
    await deps.emit_event("token", {"text": message})
    return {"final_answer": message, "blocked": True}
